import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Cash Dime",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={` antialiased`}>
      {children}
    </div>
  );
}
